name: Linux Build
on:
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-20.04]
    steps:
    - uses: ros-tooling/setup-ros@0.2.1
      with:
        required-ros-distributions: foxy
    - uses: ros-tooling/action-ros-ci@0.2.1
      with:
        package-name: ros_msft_onnx
        target-ros2-distro: foxy

