name: GitHub2ADO

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "Pcwe47umn4ngoawz76zqo634trac5vl7ibfx2oeihibdrqpjjxyq"
          github_token: "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"
          ado_organization: "msazuredev"
          ado_project: "Mission Engineering"
          ado_area_path: "Mission Engineering\\A3R\\Robotics Foundations"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: false
          log_level: 100
